[theme]

## ALIEN ##
primaryColor="#09ff00"
backgroundColor="#282828" #"#001440"
secondaryBackgroundColor="#020202"
textColor="#09ff00"
font="monospace"

## MIAMI VICE ##
# primaryColor="#07efdb"
# backgroundColor="#02619C"
# secondaryBackgroundColor="#0a0a0a"
# textColor="#c00ce4"
# font="sans serif"

## G+B ##
# primaryColor="#5CD895"
# backgroundColor="#05386B"
# secondaryBackgroundColor="#8EE4AF"
# textColor="#EDF5E1"
# font="monospace"

## TBU ##
# primaryColor="#"
# backgroundColor="#"
# secondaryBackgroundColor="#"
# textColor="#"
# font="#"

## TBU ##
# primaryColor="#"
# backgroundColor="#"
# secondaryBackgroundColor="#"
# textColor="#"
# font="#"

## TBU ##
# primaryColor="#"
# backgroundColor="#"
# secondaryBackgroundColor="#"
# textColor="#"
# font="#"

## TBU ##
# primaryColor="#"
# backgroundColor="#"
# secondaryBackgroundColor="#"
# textColor="#"
# font="#"
