[theme]

## ALIEN // MIAMI VICE
primaryColor="#07efdb"# "#09ff00" #"#07efdb"
backgroundColor="#07efdb"# "#001440" #"#02619C" #"#07efdb"
secondaryBackgroundColor="#020202" #"#0a0a0a"
textColor="#09ff00" #"#c00ce4"
font="monospace" #"sans serif"
